# *Álgebra Linear em Julia*

Esse notebook consiste em uma introdução à Álgebra Linear utlilizando Julia.
Felizmente, a linguagem já tem uma sintaxe excelente e muito paracida com Matlab. Assim,
para tornar essa exposição inicial mais motivante, vamos focar apresentar técnicas e resolver problemas
de Machine Learning que utilizam Álgebra Linear. Logo, ao seguir este notebook,
o leitor não só irá aprender a utilizar Julia, mas também aprenderá mais sobre Álgebra Linear e Machine Learning.

## **1. Declarando Vetores e Matrizes**

In [2]:
using LinearAlgebra
using CairoMakie # Biblioteca para plotagem. Existem muitas outras opções.

Veja a diferença na hora de declarar vetores versus matrizes.
O tipo "Vector" em Julia tem dimensão $(n,)$, enquanto uma "Matrix" tem, por exemplo,
$(n,1)$.

In [3]:
x = [1,2,3]
y = [1;2;3]
z = [1 2 3]
display(x) # A função display é similar a função print, só que provê melhor formatação e mostra o tipo da variável.
display(y)
display(z)

A = [1 1 0;
     1 1 1;
     0 1 0]

display(A)
println(x==y) # println é a função para printar sozinho em uma linha.
println(x==z)

3-element Vector{Int64}:
 1
 2
 3

3-element Vector{Int64}:
 1
 2
 3

1×3 Matrix{Int64}:
 1  2  3

3×3 Matrix{Int64}:
 1  1  0
 1  1  1
 0  1  0

true
false


---
Vamos mostrar algumas maneiras programáticas de declarar vetores e matrizes:

In [4]:
x = zeros(2)

2-element Vector{Float64}:
 0.0
 0.0

In [5]:
A = zeros(2,2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [6]:
A = ones(2,2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [7]:
x = fill(2.0, 3)

3-element Vector{Float64}:
 2.0
 2.0
 2.0

In [8]:
A = fill(3.0, (5,5))

5×5 Matrix{Float64}:
 3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0

In [9]:
Diagonal(A)

5×5 Diagonal{Float64, Vector{Float64}}:
 3.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅   3.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅   3.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅   3.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅   3.0

In [10]:
Diagonal(1:3)

3×3 Diagonal{Int64, UnitRange{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [11]:
I(4) # A variável I é reservada para representar a matriz identidade

4×4 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅
 ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  1

In [12]:
UpperTriangular(fill(10,(3,3)))

3×3 UpperTriangular{Int64, Matrix{Int64}}:
 10  10  10
  ⋅  10  10
  ⋅   ⋅  10

In [13]:
LowerTriangular(fill(10,(3,3)))

3×3 LowerTriangular{Int64, Matrix{Int64}}:
 10   ⋅   ⋅
 10  10   ⋅
 10  10  10

In [14]:
rand(4,4)

4×4 Matrix{Float64}:
 0.888617  0.605656  0.0563437  0.491534
 0.662143  0.877193  0.828379   0.717147
 0.989086  0.286034  0.69849    0.284398
 0.59666   0.924634  0.894482   0.965405

#### Concatenando

In [15]:
v = [1, 2]
u = [3, 4]
A = [v u]
display(A)

B = [v;u]
display(B)

2×2 Matrix{Int64}:
 1  3
 2  4

4-element Vector{Int64}:
 1
 2
 3
 4

----

## **2. Produto de Matrizes e Vetors**

Vamos agora declarar matrizes e fazer algumas contas básicas. Aqui já vai começar a ficar claro
como Julia é a linguagem ideal para Álgebra Linear.

In [70]:
v = z ⋅ x   # Escreva \cdot e aperte tab para obter esse ponto. Julia aceita unicode! Tente declarar, por exemplo, \mu
w = dot(z,x)
v == w      # O nosso ⋅ é uma maneira elegante de se escrever o produto interno.

true

In [101]:
λ = 2
M = A*λ # Multiplicando por um escalar
display(M)

u = A*x # Multiplicação por um vetor

display(A * M)  # Multiplicação matricial
display(A .* M) # Multiplicando elemento por elemento. O mesmo funciona para vetores.
                # Perceba que o "." é o operador de broadcasting, ele "vetoriza" a operação.
A + M == A .+ M # No caso da soma, por exemplo, a soma com ou sem o broadcast funciona igualmente.

3×3 Matrix{Int64}:
 1  1  0
 1  1  1
 0  1  0

3×3 Matrix{Int64}:
 2  2  0
 2  2  2
 0  2  0

3×3 Matrix{Int64}:
 4  4  2
 4  6  2
 2  2  2

3×3 Matrix{Int64}:
 2  2  0
 2  2  2
 0  2  0

true

Além do produto interno e da multiplicação de elemento a elemento, temos também o *cross product*.
Enquanto o produto interno é dado por
$$
\langle v, u \rangle = u^T v = \sum^n_{i=1} v_i u_i,
$$
o "produto vetorial" é dado por
$$
v \otimes u = v u^T =
\begin{bmatrix} 
u_1 v_1 & u_2v_1& u_3v_1\\
u_1 v_2 & u_2v_2& u_3v_2\\
u_1 v_3 & u_2v_3& u_3v_3\\
\end{bmatrix}.
$$
Diferente do produto interno para vetores reais, não temos comutativdade, ou seja,
$u\otimes v \neq v \otimes u$.

In [19]:
# Para vetores de 3 dimensões, podemos escrever o produto vetorial da usando o símbolo ×
v = [1, 2, 1]
u = [3, 4, 2]
v × u

3-element Vector{Int64}:
  0
  1
 -2

## **3. Dimensões, Rank, Diagonal, Inversa, Transposta, Exponencial, Autovalores, Autovetores...**

In [65]:
A = [1 1 2
     3 4 5
     6 7 8]

diag(A)        # Extrai valores da Diagonal

@show rank(A)  # Retorna o rank da matriz

@show A'       # Transposta

inv(A)         # Invertendo matriz
A^(-1)         # Pode-se elevar por -1 para inverter

rank(A) = 3
A' = [1 3 6; 1 4 7; 2 5 8]


3×3 Matrix{Float64}:
  1.0  -2.0        1.0
 -2.0   1.33333   -0.333333
  1.0   0.333333  -0.333333

Caso a matriz não tenha inversa, podemos utlizar a pseudo-inversa.

In [78]:
A = [0 1
     1 1
     3 4
     6 7]

# Quando a matriz A tem rank cheio, podemos calcular a pseudo-inversa
# como mostrado abaixo. Isso equivale a função `pinv` em Julia.
(A'*A)^-1*A' ≈ pinv(A)

true

In [210]:
A = Matrix(1.0I, 2, 2)

display(A)
display(exp(A))# Exponencial da matriz basta aplicar a função de exp
u = [1 1 3]


println("Traço de A =", tr(A)) # Traço da matriz
println("Determinante de A =", det(A)) # Traço da matriz
println("Dimensão de A é ", size(A))
println("Dimensão de u é ", size(u))

2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

2×2 Matrix{Float64}:
 2.71828  0.0
 0.0      2.71828

Traço de A =2.0
Determinante de A =1.0
Dimensão de A é (2, 2)
Dimensão de u é (1, 3)


Vamos calcular os autovalores e autovetores. 

In [265]:
A = [1 -1
     1  1]
λ1, λ2 = eigvals(A)
v      = eigvecs(A)
v1     = v[:,1]
v2     = v[:,2];
println(A*v1 == λ1 *v1)
println(A*v2 == λ2 *v2)
λ1, λ2 # Julia retorna números complexos!

true
true


(1.0 - 1.0im, 1.0 + 1.0im)

## **4. Slicing**
Slicing consiste em vazer "cortes" obtendo os elementos desejados de uma matriz.
Em Julia, é especialmente fácil obter colunas e linhas específicas de uma matriz. Entretanto,
como veremos a seguir, para extrair uma lista de elementos específicos é um pouco mais verboso, porém,
nada muito complexo.

In [20]:
A = [1 2 3
     4 5 6
     7 8 9]

# A[i,j] o primeiro índice é a linha e o segundo é a coluna.
A[3,1]

7

Para selecionar todas as linhas ou todas as colunas, use ":".

In [21]:
A[:,1] # Priemeira coluna

3-element Vector{Int64}:
 1
 4
 7

In [22]:
A[2,:] # Segunda linha, mas retorna como vetor

3-element Vector{Int64}:
 4
 5
 6

In [23]:
A[[2],:] # Segunda linha, mas retorna como matriz 1x3

1×3 Matrix{Int64}:
 4  5  6

Aqui as coisas ficaram um pouco mais verbosas. Se quisermos selecionar
vários elementos de uma matriz através de uma lista qualquer
de índices, infelizmente não podemos simplesmente passar uma lista
de índices como [(1,2),(1,3),(3,3)].

Uma primeira maneira de selecionar vários elementos através de uma lista de índices
é transformando esses índices em o que chamamos de LinearIndex. Em Julia,
uma matrix nxd pode ser vista como um Array de nd elementos, construida através
da concatenação de cada coluna, e.g.:
```
|1 2 3|    --- >    |1 4 2 5 3 6|
|4 5 6| 
```

Assim, `A[2] = 4`. Logo, na matriz 3x3 o índice $(i,j)$ equivale a $i + 3(j-1)$.
Podemos assim converter cada tupla em um índice linear e passar essa lista
para selecionar cada elemento.

Felizmente, existe uma forma mais elegante, utilizando `CartersianIndex`.
Esse é um tipo de variável em Julia que justamente indica que estamos
querendo selecionar um índice em uma matriz (ou em um array multidimensional.

In [76]:
A = [1 2 3
     4 5 6
     7 8 9]

indices = [(1,2),(2,3),(3,3)]
A[CartesianIndex.(indices)] # Usamos o . para fazer o broadcasting

3-element Vector{Int64}:
 2
 6
 9

Para alterar os valores da matriz, basta, por exemplo, selecionar o índice e fazer `A[1,2] = 10`.
Caso se queira modificar vários elementos ao mesmo tempo,
devemos utilizar o operador "." de broadcasting.

In [77]:
A[1,1] = 20
A

3×3 Matrix{Int64}:
 20  2  3
  4  5  6
  7  8  9

In [78]:
A[:,1] .= 10
A

3×3 Matrix{Int64}:
 10  2  3
 10  5  6
 10  8  9

In [81]:
A[1,:] .= [0,20,30]
A

3×3 Matrix{Int64}:
  0  20  30
 10   5   6
 10   8   9

Uma observação importante. Assim como em Python,
temos que ter cuidado ao copiar vetores e matrizes, pois
um simplex "x = y" irá na verdade criar uma relação entre as duas variáveis.
Observe:

In [62]:
y = [1,1,1]
x = y
x[3] = 3
display(y)

3-element Vector{Int64}:
 1
 1
 3

Usando `copy` a variável original se mantém igual. 

In [66]:
a = copy(y)
a[3] = 10
y

3-element Vector{Int64}:
 1
 1
 3

## **5 Aplicando Funções**
Algumas poucas palavras sobre a aplicação de funções. Primeiro ponto é perceber a
diferença entre aplicar a função elemento a elemento ou em toda a matriz de uma vez.
Como nos casos anteriores, o operador "." é responsável por garantir que a função
seja aplicada em cada elemento.

In [119]:
A = [1 2 3
     4 5 6
     7 8 9]
f(x) = x^2
f(A) == A*A

true

In [120]:
f.(A) # Elevando cada elemento ao quadrado.

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

Em Julia, é comum utilizar a exclamação (!) para indicar que uma função está atuando inplace.
Por exemplo, eu posso criar duas funções `myfunc` e `myfunc!`, e a comunidade de Julia irá
intuir que ambas fazem a mesma coisa, com a diferença que a segunda é inplace, ou seja,
irá modificar o valor da variável que estou passando pra ela.

In [121]:
function f!(x)
   x .= x^2    # Aqui o operador . está fazendo a função de inplace
end
A

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [122]:
f!(A)
A

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

## **6. Iterando em Vetores e Matrizes**
Vamos concluir esse notebook falando sobre como iterar nos elementos de uma matriz.
A primeira forma é clara, poderíamos simplemente escrever dois loops variando os índices `i` e `j`,
e usar `A[i,j]`. Existe, porém, uma outra forma que é mais direta de se programar.

In [30]:
size(A[1:2,:])

(2, 3)

In [49]:
A = [1 2 3
     4 5 6
     7 8 9]

# Formato 1
for i = 1:size(A)[1]      # Note que abaixo escrevemos diferente só para mostrar que Julia aceita diferentes maneiras.
    for j in 1:size(A)[2] # Aqui, podemos tanto usar o sinal "=" como "in".
        print(A[i,j])
    end
end
print(",")


# Formato 2 - Julia nos permite uma maneira limpa de escrever loops dentro de loops
for i = 1:size(A)[1], j = 1:size(A)[2]
        print(A[i,j])
end
println(",")

# Formato 3 - Aqui, o índice é no formato "corrido", lembrando que a matriz "empilha" as colunas, ou seja, para
# matriz 3x3, o índice 4 representa a linha 1 coluna 2. Já explicamos isso na seção de Slicing.
for (i,e) in enumerate(A)
    println(i,",",e)
end

# Aqui mostramos como iterar diretamente por linha e coluna.
for r in eachrow(A)
    println(r)
end

for c in eachcol(A)
    println(c)
end

123456789,123456789,
1,1
2,4
3,7
4,2
5,5
6,8
7,3
8,6
9,9
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


----
Concluímos essa seção de conceitos básico de Álgebra Linear.
Nos notebooks seguintes vamos entrar em alguns assuntos mais avançados,
como decomposição SVD. Porém, com o que foi apresentado aqui, você já poderia
programar, por exemplo, a decomposição SVD sem utilizar a função nativa de Julia.