In [1]:
import torch
from torch.autograd import Variable
N, D_in, H, D_out = 64, 1000, 100, 10

In [2]:
# produce random input data, but we dont need gradients on them
x = Variable ( torch.randn ( N, D_in ), requires_grad = False )

In [3]:
# the data, as a tensor are accessible via .data (here retrieving only 
# first ten entries of second column)
x.data[:10:,1]

tensor([ 0.9064,  0.5827, -0.2104, -0.6049, -0.4801, -0.3057, -0.7067, -0.2720,
        -0.5093,  2.3095])

In [4]:
## variables have all the convenience methods of tensors
x.clamp(min=0.)[:10:,1]

tensor([0.9064, 0.5827, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        2.3095])

In [5]:
# produce random labels, and no gradients needed on them, either
y = Variable ( torch.randn ( N, D_out ), requires_grad = False )

In [6]:
# the weights however, should remember their gradients
w1 = Variable ( torch.randn ( D_in, H ), requires_grad = True )
w2 = Variable ( torch.randn ( H, D_out ), requires_grad = True )

In [7]:
# the gradient is also a Variable, and accessible via .grad
#(but only after backprop)
print ( w1.grad )

None


In [8]:
y_pred = x.mm(w1).clamp(min=0.).mm(w2)
loss = ( y_pred - y ).pow(2).sum()

In [9]:
# all variables track their provenance
loss.backward()

In [10]:
# now we have a gradient
w1.grad[:10:,1]

tensor([  1344.9938,  -2858.6677,  19225.0352, -16002.1924,   8366.1250,
          7764.0747,  -6582.6934,   6242.3301, -18540.0879,   -685.3781])