In [1]:
import torch

In [2]:
# create a 2nd order tensor, fill with zeroes
torch.FloatTensor(3,3).zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# create a tensor from a list
t=torch.Tensor([[2.],[1.]])

In [4]:
# squeeze tensor, i.e turn a tensor with shape 
# of Ax1 into a tensor with shape A.
ts = t.squeeze()

In [5]:
# dot product (special case of matrix multiplication)
ts.dot(ts)

tensor(5.)

In [6]:
# transpose tensor
t.t()

tensor([[2., 1.]])

In [7]:
## concatenate tensors, but show only first 5 elements
torch.cat([t]*5)[:5]

tensor([[2.],
        [1.],
        [2.],
        [1.],
        [2.]])